// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MzDIwLgxR2ZIbCpPs1LR3glilrGzcT4',
    appId: '1:95821043563:web:4ad3f0cbd3184a3c9b9e2e',
    messagingSenderId: '95821043563',
    projectId: 'tickettrail-d3f58',
    authDomain: 'tickettrail-d3f58.firebaseapp.com',
    storageBucket: 'tickettrail-d3f58.appspot.com',
    measurementId: 'G-F9E0FXZHCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDncJ55Vi4fuYzSWtIomyWVYblAT3lXbpo',
    appId: '1:95821043563:android:e622609e07c720449b9e2e',
    messagingSenderId: '95821043563',
    projectId: 'tickettrail-d3f58',
    storageBucket: 'tickettrail-d3f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZko_tJzO8dPXINaHKefu9o4TPLjlFf1k',
    appId: '1:95821043563:ios:405f06df0bb465139b9e2e',
    messagingSenderId: '95821043563',
    projectId: 'tickettrail-d3f58',
    storageBucket: 'tickettrail-d3f58.appspot.com',
    iosBundleId: 'com.tickettrail.lk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZko_tJzO8dPXINaHKefu9o4TPLjlFf1k',
    appId: '1:95821043563:ios:b56c090d655f3c2e9b9e2e',
    messagingSenderId: '95821043563',
    projectId: 'tickettrail-d3f58',
    storageBucket: 'tickettrail-d3f58.appspot.com',
    iosBundleId: 'com.tickettrail.lk.RunnerTests',
  );
}
